name: docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install pnpm
        run: npm i pnpm -g

      - name: Install dependencies
        run: pnpm i

      - name: Build VuePress site
        run: pnpm docs:build

      - name: Deploy to GitHub Pages
        use: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: 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
