name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: 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
        TARGET_REPO: username/repo
        TARGET_BRANCH: master
        BUILD_SCRIPT: npm i pnpm -g && pnpm i && pnpm docs:build
        BUILD_DIR: docs/.vuepress/dist